src/admin/views.py
from flask import Blueprint, Flask, flash, redirect, render_template, url_for
from flask_login import current_user, login_required

from src.models import User

admin = Blueprint('admin', __name__, template_folder='templates',url_prefix='/admin')

is_admin = False

def isAdmin(redirectURL , template):
    if hasattr(current_user, 'is_admin'):
        if(current_user.is_admin is not True):
            flash('You are not authorized to access this page.')
            return redirect(redirectURL)
        else :
            return template
    else :
        flash('You are not authorized to access this page.')
        return redirect(redirectURL)

@admin.route('/')
@login_required
def index():
    return isAdmin(url_for('core.index'), render_template('admin/index.html'))



@admin.route('/users')
@login_required
def users():
    return isAdmin(url_for('core.index'), render_template('admin/users.html'))

src/core/views.py
from flask import render_template,Blueprint, request, redirect, url_for, flash, abort

core = Blueprint('core', __name__, template_folder='templates' ,url_prefix='/')

@core.route('/')
def index():
    
    return render_template('index/index.html')

src/user/views.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_required, login_user, logout_user
from sqlalchemy import null
from src.models import User
from src import db
from src.user.forms import LoginForm, RegistrationForms

user = Blueprint('user', __name__, template_folder='templates',url_prefix='/user')

@user.route('/login' , methods=['GET','POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash('You have been logged in.', 'success')

            next_page = request.args.get('next')
            if not next_page or next_page[0] != '/':
                next_page = url_for('core.index')

            return redirect(next_page)
    return render_template('user/login.html' , form=form)

@user.route('/logout' , methods=['GET','POST'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('user.login'))
    
@user.route('/profile/<username>' , methods=['GET','POST'])
@login_required
def profile(username):
    if username is not null:
        user = User.query.filter_by(username=username).first()
        if user is not None:
            return render_template('user/profile.html', user=user)
    return redirect(url_for('user.login'))


@user.route('/register' , methods=['GET','POST'])
def register():
    form = RegistrationForms()
    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('You are now a registered user')
        return redirect(url_for('user.login'))
    
    return render_template('user/register.html', form=form)

src/templates/layout/admin.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style href="../../static/css/main.css" rel="stylesheet"></style>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous">
    </script>
    <title>{% block title %} {% endblock %}</title>
</head>

<body>
    <header>
        <div class="container">
            <div class="row">
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <div class="container-fluid">
                      <a class="navbar-brand" href="#">Navbar</a>
                      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>
                      <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav" style="list-style-type:none">
                          <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{ url_for('admin.index') }}">Home</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('admin.users') }}">Users</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="#">Pricing</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </nav>
            </div>
        </div>
    </header>
    {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
    {% endfor %}
    {% block content %}

    {% endblock %}
</body>

</html>

src/templates/layout/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"
        integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous">
    </script>
    <link href="../../static/css/main.css" rel="stylesheet" type="text/css">
    <link href="../../static/css/semantic.min.css" rel="stylesheet" type="text/css">
    <script src="../../static/js/semantic.min.js"></script>
    <title>{% block title %} {% endblock %}</title>
</head>

<body>
    <div class="ui left demo vertical inverted sidebar labeled icon menu">
        <a class="item" href="{{ url_for('core.index') }}">
            <i class="home icon"></i>
            Home
        </a>
        <a class="item" href="{{ url_for('core.index') }}">
            <i class="address book outline icon"></i>
            Messages
        </a>
        <a class="item" href="{{ url_for('core.index') }}">
            <i class="smile icon"></i>
            Friends
        </a>
    </div>
    <header>
        <div class="container-fluid bg-dark text-white">
            <div class="row py-1">
                <div class="col-md-2 col-sm-7 col-6 d-flex flex-row justify-content-start link align-items-center">
                    <span class="sidebar toggle pe-1 pe-md-5"><i class="align justify icon"></i></span>
                    <h1 class="h4 my-auto">Simple Chat App</h1>
                </div>
                <div class="col-5 col-md-7 d-md-block d-none">

                </div>
                <div class="col-6 col-sm-5 col-md-3 ">
                    {% if current_user.is_authenticated %}
                    <a href="{{ url_for("user.profile" , username=current_user.username ) }}" class="">
                        <button class="ui icon inverted button">
                           {{current_user.username}} <i class="user outline icon"></i>
                        </button>
                    </a>
                    <a href="{{ url_for("user.logout") }}" class="">
                        <button class="ui icon inverted button">
                            <i class="power off icon"></i>
                        </button>
                    </a>
                    {% else %}
                    <a href="{{ url_for("user.login") }}" class="">
                        <button class="ui icon inverted button">
                            <i class="user outline icon"></i>
                        </button>
                    </a>
                    <a href="{{ url_for("user.register") }}" class="">
                        <button class="ui icon inverted button">
                            <i class="registered icon"></i>
                        </button>
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </header>
    {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
    {% endfor %}
    {% block content %}

    {% endblock %}
</body>


<script>
    $('.sidebar.toggle').click(function () {
        $('.ui.sidebar').sidebar('toggle');
    })
</script>

</html>