src/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField, ValidationError, TextAreaField
from wtforms.validators import DataRequired, Length, Email, EqualTo, Regexp
from wtforms import ValidationError

from flask_login import current_user
from src.models import User

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=3, max=20)])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')

class RegistrationForms(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email(), Length(min=3, max=50)])
    username = StringField('Username', validators=[DataRequired(), Length(min=3, max=20)])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=3, max=20)])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), Length(min=3, max=20), EqualTo('password',message = "Passwords must match")])
    submit = SubmitField('Sign Up')

    def checkEmail(self,field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Email already exists')
    
    def checkUsername(self,field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Username already exists')

# TODO - add a form for changing password

src/chat/views.py
from flask import Blueprint, Flask, flash, redirect, render_template, url_for
from flask_login import current_user, login_required
from src import db
from src.models import User, UserFriends, UserMessages

chat = Blueprint('chat', __name__, template_folder='templates',url_prefix='/chat')

@chat.route('/<id>/<room>')
@login_required
def index(id , room): 
    messagesAll = UserMessages.query.filter_by(user_id=current_user.id , friends_id=id ).all()
    messagesFriends = UserMessages.query.filter_by(friends_id=current_user.id , user_id=id ).all()
    messages = messagesAll + messagesFriends
    def custom_sort(message):
        return message.created_at
    messages.sort(key=custom_sort)
    return render_template('chat/index.html' , friend_id=id , messages=messages , room = room)



@chat.route('/usersadd/<id>')
@login_required
def friendAdd(id):
    freiend = UserFriends(user_id = id, room_id = current_user.id)
    db.session.add(freiend)
    db.session.commit()
    return redirect(url_for('chat.index', id=id , room = current_user.id))

@chat.route('/users')
@login_required
def users():
    user = User.query.outerjoin(UserFriends).all()
    return render_template('chat/users.html' , users=user)

src/user/views.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_required, login_user, logout_user
from sqlalchemy import null
from src.models import User
from src import db
from src.user.forms import LoginForm, RegistrationForms

user = Blueprint('user', __name__, template_folder='templates',url_prefix='/user')

@user.route('/login' , methods=['GET','POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash('You have been logged in.', 'success')

            next_page = request.args.get('next')
            if not next_page or next_page[0] != '/':
                next_page = url_for('core.index')

            return redirect(next_page)
    return render_template('user/login.html' , form=form)

@user.route('/logout' , methods=['GET','POST'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('user.login'))
    
@user.route('/profile/<username>' , methods=['GET','POST'])
@login_required
def profile(username):
    if username is not null:
        user = User.query.filter_by(username=username).first()
        if user is not None:
            return render_template('user/profile.html', user=user)
    return redirect(url_for('user.login'))


@user.route('/register' , methods=['GET','POST'])
def register():
    form = RegistrationForms()
    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('You are now a registered user')
        return redirect(url_for('user.login'))
    
    return render_template('user/register.html', form=form)

src/templates/chat/index.html
{% extends "layout/index.html" %}

{% block title %}
title
{% endblock %}
{% block content %}
<script src="//cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js"
    integrity="sha256-yr4fRk/GU1ehYJPAs8P4JlTgu0Hdsp4ZKrx8bDEDC3I=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"
    integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA=="
    crossorigin="anonymous"></script>
<script type="text/javascript" charset="utf-8">
    var socket = io();
    socket.on('connect', function () {
        socket.emit('connect_server', {
            data: 'I\'m connected!',
            room: '{{ room }}'
        });
        // socket.join('{{ room }}');
    });
</script>

<div class="ui message container mx-auto" id="messages">
    {% for message in messages %}
    {% if current_user.id == message.user_id %}
    <div class="right floated content get-message">
        <div class="ui green message">
            <div class="content content-message">
                {{ message.message }}
            </div>
        </div>
    </div>
    {% else %}
    <div class="left floated content send-message">
        <div class="ui blue message">
            <div class="content content-message">
                {{ message.message }}
            </div>
        </div>
    </div>
    {% endif %}
    {% endfor %}
</div>
<div class="container" id="chat-box-body" data-id="{{current_user.id}}" data-friend_id="{{friend_id}}">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">{{current_user.username}}</h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="chat-box">
                                <div class="chat-box-header">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <h4 class="title">Chat</h4>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="pull-right">
                                                <a href="javascript:void(0);" id="send"
                                                    class="btn btn-primary btn-round float-right" style="float: right;"
                                                    data-toggle="tooltip" data-placement="right" title="Send Message">
                                                    <i class="send icon w-25 float-right"></i>Send
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="chat-box-body">
                                    <div class="chat-box-list">
                                        <div class="chat-box-list-item">
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="chat-box-list-item-header">
                                                        <div class="row">
                                                            <div class="col-md-6">
                                                                <div class="chat-box-list-item-header-title">
                                                                    <h4 class="title"></h4>
                                                                </div>
                                                            </div>
                                                            <div class="col-md-6">
                                                                <div class="chat-box-list-item-header-time">
                                                                    <h4></h4>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="chat-box-footer">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="chat-box-footer-message">
                                                <div class="row">
                                                    <div class="col-md-12">
                                                        <div class="form-group">
                                                            <label for="message">Message</label>
                                                            <textarea class="form-control" id="message"
                                                                rows="3"></textarea>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $('#send').click(function () {
        var newMessage = $('.get-message').clone().last();
        newMessage.find('.content-message').text($('#message').val());
        newMessage.appendTo('#messages');
        socket.emit('client_message', {
            message: $('#message').val(),
            user_id: $('#chat-box-body').data('id'),
            room: '{{ room }}',
            friend_id: $('#chat-box-body').data('friend_id')
        });
    });

    socket.on('server_message', function (msg) {
        console.log($('#chat-box-body').data('id') != msg.user_id)
        if ($('#chat-box-body').data('id') != msg.user_id) {
            var newMessage = $('.send-message').clone().last();
            newMessage.find('.content-message').text(msg.message);
            newMessage.appendTo('#messages');
        }
    });
</script>

{% endblock %}

src/templates/chat/users.html
{% extends "layout/index.html" %}

{% block title %}
Kullanicilar
{% endblock %}
{% block content %}
<div class="container">
    {% for user in users %}
    {% if user.username != current_user.username %}
    <div>
        {{user.username}}
        {% if user.friends: %}
        <a class="btn btn-primary" href="{{url_for('chat.index',id=user.friends,room=user.id)}}">
            EKLE
        </a>
        {% else %}
        <a class="btn btn-primary" href="{{url_for('chat.friendAdd',id=user.id)}}">
            EKLE
        </a>
        {% endif %}
    </div>
    {% endif %}
    {% endfor %}
</div>
{% endblock %}